nginx:
  build: ./containers/nginx
  container_name: nginx
  ports:
    - "80:80"
  volumes:
    - ./conf/nginx-sites:/etc/nginx/conf.d
    - ./log/nginx:/var/log/nginx
    - ./www/drupal:/var/www/drupal
  links:
    - drupalapp1:drupalapp1


drupalapp1:
  build: ./containers/drupalapp1
  container_name: drupalapp1
  ports:
    - "9000"
  links:
    - mysql:mysql

  volumes:
    - ./www/drupal:/var/www/drupal
    #- ./log/drupalapp1:/var/log
  environment:
    - DRUPAL_BASE_DIR=drupal
    - DRUPAL_SITE_0_PROFILE=standard
    - DRUPAL_SITE_0_ACCOUNT_NAME=admin
    - DRUPAL_SITE_0_ACCOUNT_PASS=admin

    - DRUPAL_SITE_0_MYSQL_DATABASE=drupal
    - DRUPAL_SITE_0_MYSQL_USER=drupal
    - DRUPAL_SITE_0_MYSQL_PASSWORD=drupal



mysql:
  image: mysql
  container_name: mysql
  ports:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=drupal
    - MYSQL_USER=drupal
    - MYSQL_PASSWORD=drupal
